apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14

        env:
        - name: POSTGRES_DB
          value: bmidb
        - name: POSTGRES_USER
          value: bmi_user
        - name: POSTGRES_PASSWORD
          value: bmipass

        ports:
        - containerPort: 5432

        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: init-sql
        configMap:
          name: postgres-init